### ISSUE TITLE
Another NoneType error

### ISSUE THREAD

**Issue by Darkle** [vitto/sublime-theme-automator#2]
I'm getting the following error when I run the package:
```
Traceback (most recent call last):
  File "/Applications/Coding/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "ThemeAutomator in /Users/coop/Library/Application Support/Sublime Text 3/Installed Packages/ThemeAutomator.sublime-package", line 64, in on_activated
  File "ThemeAutomator in /Users/coop/Library/Application Support/Sublime Text 3/Installed Packages/ThemeAutomator.sublime-package", line 41, in add_scheme
AttributeError: 'NoneType' object has no attribute 'append'
found 12 files for base name Main.sublime-menu
Traceback (most recent call last):
  File "/Applications/Coding/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 319, in on_deactivated
    callback.on_deactivated(v)
  File "ThemeAutomator in /Users/coop/Library/Application Support/Sublime Text 3/Installed Packages/ThemeAutomator.sublime-package", line 69, in on_deactivated
  File "ThemeAutomator in /Users/coop/Library/Application Support/Sublime Text 3/Installed Packages/ThemeAutomator.sublime-package", line 51, in set_scheme_for_extension
  File "ThemeAutomator in /Users/coop/Library/Application Support/Sublime Text 3/Installed Packages/ThemeAutomator.sublime-package", line 41, in add_scheme
AttributeError: 'NoneType' object has no attribute 'append'
```
I'm not sure if it's the same thing as in this earlier bug: https://github.com/vitto/sublime-theme-automator/issues/1 as the error seems a little bit different.

When I first installed the package it worked fine, but after I restarted Sublime it no longer worked and that error shows up in the console.

My details:
OSX 10.9.4
Sublime Text 4, build 3065

**Comment by Darkle** [comment]
Just wondering if there has been any progress on this?

**Comment by vitto** [comment]
Yeah, now it should be finally fixed, thanks for the ping!

**Comment by Darkle** [comment]
Awesome! Just tried it and restarted and it's working great. Thanks.
